---
ansible_user: ansible
ansible_password: cisco

ansible_become: true
ansible_become_method: enable
ansible_become_password: cisco

ansible_network_os: cisco.ios.ios
ansible_connection: ansible.netcommon.network_cli

# Paramiko-specific settings (not OpenSSH)
ansible_paramiko_look_for_keys: false
ansible_paramiko_host_key_checking: false