---
hostname: R5
ospf_router_id: 5.5.5.5

# R5 is an ABR - connects Area 0 (HQ) to Area 1 (Branches)
interfaces:
  - name: Ethernet0/1
    description: "TO_R8_BRANCH_AREA1"
    ipv4_address: 10.1.1.13
    ipv4_netmask: 255.255.255.252
    
  - name: Ethernet0/3
    description: "TO_R4_HQ_AREA0"
    ipv4_address: 10.1.1.18
    ipv4_netmask: 255.255.255.252

  - name: Loopback0
    description: "ROUTER_ID"
    ipv4_address: 5.5.5.5
    ipv4_netmask: 255.255.255.255
    
  - name: Loopback1
    description: "SIMULATED_HQ_NETWORK"
    ipv4_address: 10.10.5.1
    ipv4_netmask: 255.255.255.0

# OSPF Configuration - R5 is ABR
ospf_networks:
  # Area 0 networks
  - network: 10.1.1.16
    wildcard: 0.0.0.3
    area: 0
  
  - network: 5.5.5.5
    wildcard: 0.0.0.0
    area: 0
    
  - network: 10.10.5.0
    wildcard: 0.0.0.255
    area: 0
  
  # Area 1 networks (ABR link)
  - network: 10.1.1.12
    wildcard: 0.0.0.3
    area: 1

ospf_passive_interfaces:
  - Loopback1