---
hostname: R4
ospf_router_id: 4.4.4.4
ospf_process_id: 1

interfaces:
  - name: Ethernet0/1
    description: "TO_R5_ABR0_AREA0"
    ipv4_address: 10.10.20.2
    ipv4_netmask: 255.255.255.252

  - name: Loopback0
    description: "ROUTER_ID"
    ipv4_address: 4.4.4.4
    ipv4_netmask: 255.255.255.255

ospf_networks:
  - network: 10.10.20.0
    wildcard: 0.0.0.3
    area: 0
    
  - network: 10.10.20.4
    wildcard: 0.0.0.3
    area: 0
  
  - network: 4.4.4.4
    wildcard: 0.0.0.0
    area: 0
    
  - network: 172.16.47.0
    wildcard: 0.0.0.255
    area: 0

ospf_passive_interfaces:
  - Loopback1