---
hostname: R8
ospf_router_id: 8.8.8.8
ospf_process_id: 1

interfaces:
  - name: Ethernet0/1
    description: "TO_R7_AREA1"
    ipv4_address: 10.10.10.1
    ipv4_netmask: 255.255.255.252
    
  - name: Ethernet0/2
    description: "TO_R9_AREA1"
    ipv4_address: 10.10.10.5
    ipv4_netmask: 255.255.255.252

  - name: Loopback0
    description: "ROUTER_ID"
    ipv4_address: 8.8.8.8
    ipv4_netmask: 255.255.255.255

ospf_networks:
  # Area 1 networks
  - network: 10.10.10.0
    wildcard: 0.0.0.3
    area: 1
    
  - network: 10.10.10.4
    wildcard: 0.0.0.3
    area: 1
   
  - network: 8.8.8.8
    wildcard: 0.0.0.0
    area: 1
  
  # ABR link to R5 (configured in Phase 2)
  - network: 203.0.113.0
    wildcard: 0.0.0.3
    area: 0

ospf_passive_interfaces: []