---
hostname: R2

ospf_router_id: 2.2.2.2

interfaces:
  - name: Ethernet0/1
    description: "TO_R1_AREA0_BACKBONE"
    ipv4_address: 10.1.12.2
    ipv4_netmask: 255.255.255.252

  - name: Loopback0
    description: "ROUTER_ID"
    ipv4_address: 2.2.2.2
    ipv4_netmask: 255.255.255.255
    
  - name: Loopback1
    description: "SIMULATED_LAN"
    ipv4_address: 10.10.2.1
    ipv4_netmask: 255.255.255.0

# OSPF Configuration - R2 is in Area 0 only
ospf_networks:
  - network: 10.1.12.0
    wildcard: 0.0.0.3
    area: 0
    
  - network: 2.2.2.2
    wildcard: 0.0.0.0
    area: 0
    
  - network: 10.10.2.0
    wildcard: 0.0.0.255
    area: 0

ospf_passive_interfaces:
  - Loopback1